name: fetch-changed
description: GitHub action to fetch a list of changed files between the previous commits and the current commits
author: Kalrnlo

branding:
  icon: list
  color: purple

inputs:
  token:
    description: "GitHub token via `github.token`"
    default: "${{ github.token }}"
    required: false

outputs:
  files_changed:
    description: A multi-line string containing the list of changed files.
    value: ${{ steps.main.outputs.diff }}

runs:
  using: "composite"
  steps:
    - name: Main
      shell: bash
      id: main
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        case "${{ github.event_name }}" in
          push)
            commits_len=${{ github.event.commits }}[*]
            diff = "$(gh api "repos/${{github.repository}}/compare/${{ github.event.commits[commits_len].id }}...${{ github.event.commits[0].id }}" --jq ".files[].filename")";
            ;;
          pull_request)
            diff = "$(gh api "repos/${{ github.event.pull_request.base.repo.full_name }}/compare/${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.label }}" --jq ".files[].filename")";
            ;;
        esac

        echo "diff=$diff" >> $GITHUB_OUTPUT
        echo diff >> .diff