name: fetch-changed
description: GitHub action to fetch a list of changed files between the previous commits and the current commits
author: Kalrnlo

branding:
  icon: list
  color: purple

inputs:
  token:
    description: "GitHub token via `github.token`"
    default: "${{ github.token }}"
    required: false

outputs:
  files_changed:
    description: A multi-line string containing the list of changed files.
    value: ${{ steps.main.outputs.diff }}

runs:
  using: "composite"
  steps:
    - name: Main
      shell: bash
      id: main
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        case '${{ github.event_name }}' in
          push)
            firstCommit='${{ github.event.commits[0].id }}'
            lastCommit='${{ github.event.commits[-1].id }}'
            ;;
          pull_request)
            firstCommit='${{ github.event.base_ref }}'
            lastCommit='${{ github.event.head_ref }}'
            ;;
        esac
        diff=$(git diff --name-only --diff-filter=d ${firstCommit}~1 ${lastCommit})
        echo "diff=$diff" >> $GITHUB_OUTPUT
        echo diff >> .diff