name: Fetch Diff
description: GitHub action to fetch a diff between the previous commits and the current commits
author: kalrnlo

branding:
  icon: list
  color: purple

inputs:
  token:
    description: "GitHub token via `github.token`"
    default: "${{ github.token }}"
    required: false

outputs:
  files_changed:
    description: A multi-line string containing the list of changed files.
    value: ${{ steps.main.outputs.diff }}

runs:
  using: "composite"
  steps:
    - name: Main
      shell: bash
      id: main
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        case "${{ github.event_name }}" in
          push)
            previous=${{ github.event.commits[-1].id }}
            latest=${{ github.event.commits[0].id }}

            diff = gh api "repos/${{github.repository}}/compare/$previous...$latest" --jq .files[].path
            ;;
          pull_request)
            base_repo=${{github.event.pull_request.base.repo.full_name}}
            base_sha=${{github.event.pull_request.base.sha}}
            label=${{github.event.pull_request.head.label}}

            diff = gh api "repos/$base_repo/compare/$base_sha...$label" --jq .files[].path'
            ;;
        esac

        echo "diff=$diff" >> $GITHUB_OUTPUT
        echo diff >> .diff